create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  bio text,
  avatar_url text,
  background_url text,
  theme text default 'Galaxy',
  plan text default 'free',
  branding boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.follows (
  follower_id uuid references auth.users(id) on delete cascade,
  following_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (follower_id, following_id)
);

create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  profile_id uuid references auth.users(id) on delete cascade,
  author_id uuid references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.follows enable row level security;
alter table public.guestbook enable row level security;


create policy "Profiles are public"
on public.profiles
for select
using (true);


create policy "Users can create their profile"
on public.profiles
for insert
with check (auth.uid() = id);


create policy "Users can update their profile"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);


create policy "Users can delete their profile"
on public.profiles
for delete
using (auth.uid() = id);


create policy "Follows are public"
on public.follows
for select
using (true);


create policy "Users can follow"
on public.follows
for insert
with check (auth.uid() = follower_id);


create policy "Users can unfollow"
on public.follows
for delete
using (auth.uid() = follower_id);


create policy "Guestbook is public"
on public.guestbook
for select
using (true);


create policy "Users can write guestbook messages"
on public.guestbook
for insert
with check (auth.uid() = author_id);
